/* global window, localStorage */
/**
 * invoices-data.js — Supabase data-laag voor de BS2 employee-invoice
 * module (top-bar Facturen → Te beoordelen / Alle facturen). 1-op-1 BS2
 * `/api/invoices`. STRIKT LOS van `facturen-data.js` (Cliënten →
 * Beschikkingen → Facturen, disposition-model) — die wordt niet geraakt.
 *
 * Bron-van-waarheid: public.invoices (+ invoice_billing_fields,
 * invoice_workflow_transitions). Totalen komen VERBATIM uit BS2 (regel
 * total = price×amount; total_excl_vat = Σ regels) — niet herrekenen.
 *
 * DATA-SLIM: alleen lichte factuur-velden in de localStorage-cache;
 * zware billing_fields/shift-jsonb + workflow worden on-demand per
 * factuur opgehaald. _mem = in-memory bron zodat de pagina ook werkt
 * bij volle localStorage-quota.
 *
 * Public API:
 *   invoicesDB.ready / .refresh()
 *   invoicesDB.getAllSync()                 → facturen (licht)
 *   invoicesDB.getByIdSync(id)
 *   invoicesDB.getBillingFields(id)         → Promise<regels[]>
 *   invoicesDB.getWorkflow(id)              → Promise<transitions[]>
 *   invoicesDB.getRawBs2(id)                → Promise<volledige BS2-raw>
 *   invoicesDB.approve(id, comment)
 *   invoicesDB.reject(id, comment)
 *   invoicesDB.markUnderReview(id, comment)
 *   invoicesDB.archive(id) / .restore(id)
 *
 * Event: "besa:invoices-updated" op window.
 */
(function (global) {
  "use strict";

  var T_INV = "invoices";
  var T_BF = "invoice_billing_fields";
  var T_WF = "invoice_workflow_transitions";
  var CACHE = "invoices_v1";

  function reportSilent(action, err) {
    try { console.error("[invoicesDB] " + action + " mislukt:", err); } catch (e) { /* */ }
    if (global.besaReportSyncFailure) global.besaReportSyncFailure("Facturen — " + action, err);
  }
  function readCache() {
    try { var p = JSON.parse(localStorage.getItem(CACHE) || "[]"); return Array.isArray(p) ? p : []; }
    catch (e) { return []; }
  }
  function writeCache(items) {
    try { localStorage.setItem(CACHE, JSON.stringify(Array.isArray(items) ? items : [])); }
    catch (e) { /* quota — _mem is de bron */ }
  }
  function dispatchUpdated(src) {
    try { global.dispatchEvent(new CustomEvent("besa:invoices-updated", { detail: { source: src || "invoices-data" } })); }
    catch (e) { /* */ }
  }

  var _inv = null;            // in-memory lichte facturen
  var _bf = {};               // invId → regels[] (on-demand)
  var _wf = {};               // invId → transitions[] (on-demand)
  function setInv(items) { _inv = Array.isArray(items) ? items : []; writeCache(_inv); }
  function invList() { return (_inv !== null) ? _inv : readCache(); }

  function invRowToObj(r) {
    if (!r) return null;
    return {
      id: r.id,
      number: r.number || "",
      jaar: r.jaar, maand: r.maand,
      periodFormatted: r.period_formatted || "",
      totalExclVat: r.total_excl_vat == null ? 0 : Number(r.total_excl_vat),
      total: r.total == null ? 0 : Number(r.total),
      vatHandling: r.vat_handling || "regular",
      status: r.status || "draft",
      priority: r.priority || "normal",
      organization: r.organization || null,
      employee: r.employee || null,
      client: r.client || null,
      contactPerson: r.contact_person || null,
      invoiceDate: r.invoice_date || null,
      expirationDate: r.expiration_date || null,
      pdf: r.pdf || null,
      sentAt: r.sent_at || null,
      submittedAt: r.submitted_at || null,
      rejectedAt: r.rejected_at || null,
      approvedAt: r.approved_at || null,
      canBeSubmitted: !!r.can_be_submitted,
      canBeEdited: !!r.can_be_edited,
      canBeApproved: !!r.can_be_approved,
      canBeRejected: !!r.can_be_rejected,
      canBeMarkedUnderReview: !!r.can_be_marked_under_review,
      systemGeneratedSummary: r.system_generated_summary || null,
      gearchiveerd: !!r.gearchiveerd,
      deletedAt: r.deleted_at || null,
      aanmaakdatum: r.aanmaakdatum, laatstGewijzigd: r.laatst_gewijzigd,
    };
  }
  function bfRowToObj(r) {
    if (!r) return null;
    return {
      id: r.id, invoiceId: r.invoice_id,
      naam: r.naam || "", title: r.title || "", description: r.description || "",
      unit: r.unit || "", price: Number(r.price) || 0, amount: Number(r.amount) || 0,
      total: Number(r.total) || 0, sortOrder: r.sort_order == null ? 0 : Number(r.sort_order),
      product: r.product || null, comments: r.comments || null,
      isGroup: !!r.is_group, isBlankRow: !!r.is_blank_row, isAutoGenerated: !!r.is_auto_generated,
      shift: r.shift || null,
    };
  }

  var INV_COLS =
    "id,number,jaar,maand,period_formatted,total_excl_vat,total,vat_handling," +
    "status,priority,organization,employee,client,contact_person,invoice_date," +
    "expiration_date,pdf,sent_at,submitted_at,rejected_at,approved_at," +
    "can_be_submitted,can_be_edited,can_be_approved,can_be_rejected," +
    "can_be_marked_under_review,system_generated_summary,gearchiveerd,deleted_at," +
    "aanmaakdatum,laatst_gewijzigd";

  async function fetchInvoices() {
    if (!global.besaSupabase) throw new Error("Supabase client niet geladen");
    var res = await global.besaSupabase
      .from(T_INV).select(INV_COLS)
      .order("submitted_at", { ascending: false, nullsFirst: false })
      .order("aanmaakdatum", { ascending: false });
    if (res.error) throw res.error;
    return (res.data || []).map(invRowToObj).filter(Boolean);
  }

  var readyPromise = null;
  function bootstrap() {
    if (readyPromise) return readyPromise;
    if (readCache().length) dispatchUpdated("cache");
    readyPromise = (async function () {
      try { setInv(await fetchInvoices()); dispatchUpdated("bootstrap"); }
      catch (err) { reportSilent("Bootstrap", err); }
    })();
    return readyPromise;
  }
  async function refresh() { setInv(await fetchInvoices()); dispatchUpdated("refresh"); return invList(); }

  function getAllSync() { return invList(); }
  function getByIdSync(id) {
    if (id == null) return null;
    var s = String(id), f = invList().find(function (r) { return r && String(r.id) === s; });
    return f ? Object.assign({}, f) : null;
  }

  async function getBillingFields(invId) {
    if (invId == null) return [];
    var s = String(invId);
    if (_bf[s]) return _bf[s];
    if (!global.besaSupabase) return [];
    var res = await global.besaSupabase.from(T_BF)
      .select("id,invoice_id,naam,title,description,unit,price,amount,total,sort_order,product,comments,is_group,is_blank_row,is_auto_generated,shift")
      .eq("invoice_id", invId)
      .order("sort_order", { ascending: true });
    if (res.error) { reportSilent("Regels laden", res.error); return []; }
    _bf[s] = (res.data || []).map(bfRowToObj).filter(Boolean);
    return _bf[s];
  }
  async function getWorkflow(invId) {
    if (invId == null) return [];
    var s = String(invId);
    if (_wf[s]) return _wf[s];
    if (!global.besaSupabase) return [];
    var res = await global.besaSupabase.from(T_WF)
      .select("id,invoice_id,status,comment,user_id,user_name,created_at,data")
      .eq("invoice_id", invId)
      .order("created_at", { ascending: true });
    if (res.error) { reportSilent("Workflow laden", res.error); return []; }
    _wf[s] = res.data || [];
    return _wf[s];
  }
  async function getRawBs2(invId) {
    if (!global.besaSupabase || invId == null) return null;
    var res = await global.besaSupabase.from(T_INV).select("data").eq("id", invId).single();
    if (res.error) throw res.error;
    var d = res.data && res.data.data;
    return (d && d.bs2_scrape) || null;
  }

  function currentUser() {
    try {
      var p = global.profilesDB && global.profilesDB.getCurrentSync && global.profilesDB.getCurrentSync();
      if (p) return { id: p.id || null, name: ((p.voornaam || "") + " " + (p.achternaam || "")).trim() || p.email || "Onbekend" };
    } catch (e) { /* */ }
    return { id: null, name: "Onbekend" };
  }

  function genId() {
    try { if (global.crypto && global.crypto.randomUUID) return global.crypto.randomUUID(); }
    catch (e) { /* */ }
    return "wf-" + Date.now() + "-" + Math.random().toString(16).slice(2, 10);
  }

  // Status-overgang + workflow-log (1-op-1 BS2 can_be_*-matrix).
  // dataPayload (optioneel) = gestructureerde context bij de overgang
  // (bv. welke dienst(en) niet kloppen bij een afwijzing) → workflow.data jsonb.
  async function transition(id, newStatus, comment, flagPatch, stampField, dataPayload) {
    if (!global.besaSupabase) throw new Error("Supabase client niet geladen");
    var nowIso = new Date().toISOString();
    var patch = Object.assign({
      status: newStatus,
      can_be_submitted: false, can_be_edited: false, can_be_approved: false,
      can_be_rejected: false, can_be_marked_under_review: false,
      laatst_gewijzigd: nowIso,
    }, flagPatch || {});
    if (stampField) patch[stampField] = nowIso;
    var up = await global.besaSupabase.from(T_INV).update(patch).eq("id", id);
    if (up.error) throw up.error;
    var u = currentUser();
    var wfRow = {
      id: genId(), invoice_id: id, status: newStatus,
      comment: comment || null, user_id: u.id, user_name: u.name, created_at: nowIso,
      data: dataPayload || null,
    };
    var ins = await global.besaSupabase.from(T_WF).insert(wfRow);
    if (ins.error) throw ins.error;
    // _mem bijwerken (alleen de gewijzigde velden patchen)
    var arr = invList();
    for (var i = 0; i < arr.length; i++) {
      if (arr[i] && String(arr[i].id) === String(id)) {
        arr[i] = Object.assign({}, arr[i], {
          status: newStatus,
          canBeSubmitted: !!patch.can_be_submitted,
          canBeEdited: !!patch.can_be_edited,
          canBeApproved: !!patch.can_be_approved,
          canBeRejected: !!patch.can_be_rejected,
          canBeMarkedUnderReview: !!patch.can_be_marked_under_review,
          laatstGewijzigd: nowIso,
          approvedAt: stampField === "approved_at" ? nowIso : arr[i].approvedAt,
          rejectedAt: stampField === "rejected_at" ? nowIso : arr[i].rejectedAt,
        });
        break;
      }
    }
    setInv(arr);
    if (_wf[String(id)]) _wf[String(id)].push(wfRow);
    dispatchUpdated("transition");
  }

  function approve(id, comment) {
    return transition(id, "approved", comment || "Invoice approved", {}, "approved_at");
  }
  function reject(id, comment, meta) {
    return transition(id, "rejected", comment || "Invoice rejected",
      { can_be_submitted: true, can_be_edited: true }, "rejected_at", meta || null);
  }
  function markUnderReview(id, comment) {
    return transition(id, "under_review", comment || "Marked under review",
      { can_be_approved: true, can_be_rejected: true });
  }

  async function setArchived(id, val) {
    if (!global.besaSupabase) throw new Error("Supabase client niet geladen");
    var nowIso = new Date().toISOString();
    var res = await global.besaSupabase.from(T_INV)
      .update({ gearchiveerd: !!val, deleted_at: val ? nowIso : null, laatst_gewijzigd: nowIso })
      .eq("id", id);
    if (res.error) throw res.error;
    var arr = invList();
    for (var i = 0; i < arr.length; i++) {
      if (arr[i] && String(arr[i].id) === String(id)) {
        arr[i] = Object.assign({}, arr[i], { gearchiveerd: !!val, deletedAt: val ? nowIso : null });
        break;
      }
    }
    setInv(arr);
    dispatchUpdated(val ? "archive" : "restore");
  }
  function archive(id) { return setArchived(id, true); }
  function restore(id) { return setArchived(id, false); }

  global.invoicesDB = {
    get ready() { return readyPromise || bootstrap(); },
    refresh: refresh,
    getAllSync: getAllSync,
    getByIdSync: getByIdSync,
    getBillingFields: getBillingFields,
    getWorkflow: getWorkflow,
    getRawBs2: getRawBs2,
    approve: approve,
    reject: reject,
    markUnderReview: markUnderReview,
    archive: archive,
    restore: restore,
  };

  bootstrap();
})(typeof window !== "undefined" ? window : this);
